version: '2'
services:
    psi-app:
        image: psi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://psi-mysql:3306/psi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    psi-mysql:
        extends:
            file: mysql.yml
            service: psi-mysql
